//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherTodayDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherDetail
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string CountryName { get; set; }
        public decimal Temperature { get; set; }
        public int Humidity { get; set; }
        public int Visibility { get; set; }
    }
}
