//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherTodayDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WeatherDBEntities : DbContext
    {
        public WeatherDBEntities()
            : base("name=WeatherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<WeatherDetail> WeatherDetails { get; set; }
    
        public virtual ObjectResult<GETALLCITYWEATHER_Result> GETALLCITYWEATHER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETALLCITYWEATHER_Result>("GETALLCITYWEATHER");
        }
    
        public virtual ObjectResult<GETWEATHERBYCITY_Result> GETWEATHERBYCITY(string cITY)
        {
            var cITYParameter = cITY != null ?
                new ObjectParameter("CITY", cITY) :
                new ObjectParameter("CITY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETWEATHERBYCITY_Result>("GETWEATHERBYCITY", cITYParameter);
        }
    }
}
